### ISSUE TITLE
db_upgrade using Microsoft SQL failing

### ISSUE THREAD

**Issue by renek95** [amusarra/liferay-portal-database-all-in-one-support#13]
Hello!

Has anyone successfully upgrade his liferay database using the provided db_upgrade.bat in combination with mssql-drivers? I tried today and I am failing right now. I am getting the following error.

![Screenshot 2022-06-15 at 16 22 09](https://user-images.githubusercontent.com/8491599/173851002-39023a98-3cbe-4f4d-b12f-4643d40870de.png)

If there is anybody out there who did this successfully or anybody has any idea how I could fix this please reach out to me.

Sincerelly,

RK

**Comment by amusarra** [comment]
Hi @renek95 
Which version of Liferay are you referring to?
What version of SQL Server are you using?
I don't see any class on the stack trace referencing the project's MS SQL driver. I don't want it to be any problem with some Liferay specific upgrade process.

**Comment by renek95** [comment]
Hello!
Thanks for your answer. I am running on 7.3 trying to upgrade to 7.4
I used verion 7.4.3.28-ga28 to upgrade.
Had no problems on a testsystem with postgres but now with Microsoft SQL I am facing the mentioned error.

**Comment by nelsongustavo** [comment]
Same here guys

**Comment by tonuccijkl** [comment]
I had a similar problem because the library di d not implement the removePrimaryKey method for SQL server.
I added it in a for here https://github.com/tonuccijkl/liferay-portal-database-all-in-one-support

I'm totally new to github so probably I'm not following the right workflow, please feel free to correct me :)

**Comment by amusarra** [comment]
Hi @tonuccijkl 
Thanks for yours fix.

I kindly ask you to do a PR (pull request) on this repository and then I'll make the new release on Maven. 

Thank you so much.

**Comment by tonuccijkl** [comment]
Just opened, hope it's ok.

Grazie!

**Comment by amusarra** [comment]
@tonuccijkl and @renek95 just published the release 1.2.3 on the Maven Central https://central.sonatype.com/artifact/it.dontesta.labs.liferay.portal.db/liferay-portal-database-all-in-one-support/1.2.3

Thanks @tonuccijkl for your contribution.

I close this issue.
