### ISSUE TITLE
Liferay 7.2.1 GA2 mssql driver support

### ISSUE THREAD

**Issue by randomcommandline** [amusarra/liferay-portal-database-all-in-one-support#2]
Your liferay all-in-one-support driver states support up to Liferay 7.2 GA1. Do you have a driver that is compatible with Liferay 7.2.1 GA2. The following is working for me, but I would like to upgrade to 7.2.1 GA2. Thank you.

Current Working Environment:
Liferay 7.2.0 GA1
MSSQL 2014
Java 1.8.0_241
/tomcat/lib/ext/sqldbc42.jar
/tomcat/webapps/ROOT/WEB-INF/lib/liferay-portal-sqlserverdb-support-1.0-SNAPSHOT.jar

**Comment by amusarra** [comment]
Hi @randomcommandline 
You are able to make a test of the driver on 7.2 GA? Or You already tested with errors?

**Comment by randomcommandline** [comment]
Are you in the process of making version 1.1.4 available on Maven repository?  Thank you for all the work you do.

**Comment by amusarra** [comment]
Hi @randomcommandline 
I just sent the new version 1.1.4 to the Maven repository. It should be available in a few hours.

Let me know if it will work.

![Schermata 2020-03-06 alle 18 19 27](https://user-images.githubusercontent.com/708110/76106867-03d3ac80-5fd8-11ea-880b-bc3c1e016e77.png)

**Comment by amusarra** [comment]
Hi @randomcommandline 
Now you can download the driver from maven repository.
![15F92E49-94F3-4E2A-A331-DE9157979F7D](https://user-images.githubusercontent.com/708110/76146988-4eb4f900-6098-11ea-9b63-176b859cb209.png)
